# Generated by Django 5.2.4 on 2025-07-22 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authenticator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auth_name", models.CharField(max_length=200, unique=True)),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("fullـaccess", models.BooleanField()),
                ("server_name", models.CharField(max_length=200)),
                ("IPـaddress", models.GenericIPAddressField(protocol="IPv4")),
                (
                    "create_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date created"
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
    ]
