# Generated by Django 5.2.4 on 2025-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticator",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
