# Generated by Django 5.2.4 on 2025-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_app_app_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
